In [1]:
import pandas as pd
import numpy as np 
from numpy import dot
from numpy.linalg import norm
import re

In [2]:
data_df=pd.read_csv('/Users/vithulanv/MSC/Research/document-clustering/src/processed_data/reviewed/aggregated_data_with_cat_reviewed.csv')
data_df.head(15)

,title,content,url,date,category,file_name,language,covid,health,political,...,sports,economic,general,education,lifestyle,business,tech,auto,entertainment,arts
0,"Daily Covid-19 cases count hits 1,273 today","The Health Ministry says that another 1,273 pe...",http://www.adaderana.lk/news/80703/daily-covid...,2022-02-19,"covid, health",data/valid_records/Tharusha_64.json,en,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,இந்தியாவுக்கு விரைவில் வருகை தரும் இலங்கை நிதி...,"இலங்கை நிதி அமைச்சர் பஷில் ராஜபக்ஷ, இந்தியாவிற...",https://www.bbc.com/tamil/topics/cz74k7p3qw7t,2022-02-23,political,data/valid_records/Kajaani_tamil_124.json,ta,0,0,1,...,0,1,0,0,0,0,0,0,0,0
2,Met. Dept. issues advisory for severe lightning,Thundershowers accompanied by severe lightning...,http://www.adaderana.lk/news/80850/met-dept-is...,2022-02-26,weather,data/valid_records/Yathursiya_en_117.json,en,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,யாழிலிருந்து முல்லைத்தீவு சென்று தாக்குதல் மேற...,யாழ்ப்பாணத்திலிருந்து முல்லைத்தீவு – அலம்பில் ...,https://www.newsfirst.lk/tamil/2022/02/22/%e0%...,2022-02-22,"crime,legal",data/valid_records/Kajaani_tamil_42.json,ta,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,இந்திய அணிக்கு 184 ஓட்டங்கள் வெற்றி இலக்கு,இந்தியா மற்றும் இலங்கை அணிகளுக்கிடையிலான இரண்ட...,https://www.hirunews.lk/sooriyanfmnews/298140/...,2022-02-26,sports,data/valid_records/Yathursiya_tamil_124.json,ta,0,0,0,...,1,0,0,0,0,0,0,0,0,0
5,Wanindu Hasaranga : SLC official update,"Wanindu Hasaranga, who was in isolation after ...",https://www.cricwire.lk/2022/02/23/wanindu-has...,2022-02-23,"sports,covid",data/valid_records/Kajaani_eng_71.json,en,1,0,0,...,1,0,0,0,0,0,0,0,0,0
6,தேசிய பணம் அனுப்பும் மொபைல் செயலியான 'லங்கா ரெ...,நாட்டிற்கு உள்நோக்கி பணம் அனுப்புவதற்கு வசதியா...,http://tamil.adaderana.lk/news.php?nid=157761,2021-02-21,economic,data/valid_records/Yathursiya_tamil_65.json,ta,0,0,0,...,0,1,0,0,0,0,0,0,0,0
7,Enjoining Order preventing Nursing Trade Union...,The Colombo District Court today further exten...,https://www.dailymirror.lk/latest_news/Enjoini...,2022-02-25,legal,data/valid_records/Tharusha_217.json,en,0,1,0,...,0,0,0,0,0,0,0,0,0,0
8,ප්‍රදේශ කිහිපයකට තරමක තද වැසි,"නැගෙනහිර සහ ඌව පළාත්වලත් පොළොන්නරුව, මාතලේ සහ ...",http://sinhala.adaderana.lk/news/164631/%E0%B6...,2022-02-27,weather,data/valid_records/Yathursiya_sin_29.json,si,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,Pakistan names 88 suspects in Priyantha Kumara...,Police in Sialkot have submitted a challan to ...,https://ceylontoday.lk/news/pakistan-names-88-...,2022-02-27,crime,data/valid_records/Kajaani_eng_162.json,en,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,අද විදුලි කප්පාදුව සිදුවන ප්‍රදේශ,අද (06) දිනයේත්‌ පැය දෙකහමාරක්‌ සඳහා විදුලිය ක...,http://sinhala.adaderana.lk/news/164940/%E0%B6...,2022-03-06,general,data/valid_records/Tharusha_352.json,si,0,0,0,...,0,1,0,0,0,0,0,0,0,0
11,Man murdered and body burnt inside house in Ku...,A person has been found murdered and his body ...,http://www.adaderana.lk/news/80564/man-murdere...,2022-02-13,crime,data/valid_records/Tharusha_186.json,en,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,இலங்கை நிலைபெறுதகு வலு அதிகார சபைக்கு ஜனாதிபதி...,இலங்கை நிலைபெறுதகு வலு அதிகார சபைக்கு ஜனாதிபத...,https://www.newsfirst.lk/tamil/2022/02/18/%e0%...,2022-02-18,"economic,general",data/valid_records/Kajaani_tamil_173.json,ta,0,0,1,...,0,1,0,0,0,0,0,0,0,0
13,257 more patients recover from novel coronavirus,A total of 257 more patients have recovered fr...,http://www.adaderana.lk/news/80779/257-more-pa...,2022-02-23,"health, covid",data/valid_records/Tharusha_33.json,en,1,1,0,...,0,0,0,0,0,0,0,0,0,0
14,Another 125 schools to become National Schools,Sri Lanka’s Ministry of Education said that an...,https://www.newsfirst.lk/2022/02/18/another-12...,2022-02-18,education,data/valid_records/Akesh_12_en.json,en,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [11]:
valid_categories = ['general', 'crime', 'political', 'business', 'economic', 'sports', 'arts', 'entertainment',
                    'education', 'tech', 'auto', 'legal', 'lifestyle', 'health', 'covid', 'weather']

In [12]:
for i, row in data_df.iterrows():
    categories_arr = []
    for cat in valid_categories:
        if row[cat] == 1:
            categories_arr.append(cat)
    data_df.at[i, 'category'] = categories_arr

In [16]:
data_df.head()

,title,content,url,date,category,file_name,language,covid,health,political,...,sports,economic,general,education,lifestyle,business,tech,auto,entertainment,arts
0,"Daily Covid-19 cases count hits 1,273 today","The Health Ministry says that another 1,273 pe...",http://www.adaderana.lk/news/80703/daily-covid...,2022-02-19,"[health, covid]",data/valid_records/Tharusha_64.json,en,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,இந்தியாவுக்கு விரைவில் வருகை தரும் இலங்கை நிதி...,"இலங்கை நிதி அமைச்சர் பஷில் ராஜபக்ஷ, இந்தியாவிற...",https://www.bbc.com/tamil/topics/cz74k7p3qw7t,2022-02-23,"[political, economic]",data/valid_records/Kajaani_tamil_124.json,ta,0,0,1,...,0,1,0,0,0,0,0,0,0,0
2,Met. Dept. issues advisory for severe lightning,Thundershowers accompanied by severe lightning...,http://www.adaderana.lk/news/80850/met-dept-is...,2022-02-26,[weather],data/valid_records/Yathursiya_en_117.json,en,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,யாழிலிருந்து முல்லைத்தீவு சென்று தாக்குதல் மேற...,யாழ்ப்பாணத்திலிருந்து முல்லைத்தீவு – அலம்பில் ...,https://www.newsfirst.lk/tamil/2022/02/22/%e0%...,2022-02-22,[crime],data/valid_records/Kajaani_tamil_42.json,ta,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,இந்திய அணிக்கு 184 ஓட்டங்கள் வெற்றி இலக்கு,இந்தியா மற்றும் இலங்கை அணிகளுக்கிடையிலான இரண்ட...,https://www.hirunews.lk/sooriyanfmnews/298140/...,2022-02-26,[sports],data/valid_records/Yathursiya_tamil_124.json,ta,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [8]:
filtered_df = data_df[['title', 'content', 'category']]

In [9]:
filtered_df.head()

,title,content,category
0,"Daily Covid-19 cases count hits 1,273 today","The Health Ministry says that another 1,273 pe...","[health, covid]"
1,இந்தியாவுக்கு விரைவில் வருகை தரும் இலங்கை நிதி...,"இலங்கை நிதி அமைச்சர் பஷில் ராஜபக்ஷ, இந்தியாவிற...","[political, economic]"
2,Met. Dept. issues advisory for severe lightning,Thundershowers accompanied by severe lightning...,[weather]
3,யாழிலிருந்து முல்லைத்தீவு சென்று தாக்குதல் மேற...,யாழ்ப்பாணத்திலிருந்து முல்லைத்தீவு – அலம்பில் ...,[crime]
4,இந்திய அணிக்கு 184 ஓட்டங்கள் வெற்றி இலக்கு,இந்தியா மற்றும் இலங்கை அணிகளுக்கிடையிலான இரண்ட...,[sports]

In [10]:
filtered_df.to_csv('iaa_calc_export.csv')

# Cohen's Kappa Calculation

In [20]:
rater1 = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,0,0,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1]
rater2 = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,1,0,1,1,1,1,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,0,0,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1]

In [18]:
from sklearn.metrics import cohen_kappa_score

In [21]:
cohen_kappa_score(rater1, rater2)

0.8767835194784375